### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by amboar**
Signed-off-by: Andrew Jeffery <andrew@aj.id.au>

### CODE REVIEW

**Comment by goetzk** [comment]
I'm not generally a fan of these kinds of documents but given the potentially contencous nature of this project and the dispute it could cause I will +1 in this instance.
@mazzone barring an objection from you I'll merge this tomorrow.

**Comment by amboar** [comment]
probably the most controversial bit is the fact that the point of contact is a twitter handle. I need to get a useful mail configuration going for the domain

**Comment by mazzone** [comment]
Looks good to me. I also think an email address would be better than a Twitter handle, but that can be amended later!

**Comment by goetzk** [comment]
On 3/2/20 21:11, Andrew Jeffery wrote:
> probably the most controversial bit is the fact that the point of 
> contact is a twitter handle. I need to get a useful mail configuration 
> going for the domain
> 

Your registrar will usually (often?) offer a free redirect service, if 
yours doesn't let me know and we'll try and set you up a mailbox.

kk

**Comment by amboar** [comment]
Yeah I'm not sure what I got, the main problem is I haven't looked 🙂 There's an MX record so I probably have something basic

**Pull request merged**
