### PR TITLE
Fix link to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mazzone**

### CODE REVIEW

**Comment by amboar** [comment]
Ah, this one was actually correct as it was. There's a `permalink: /contributing/` in CONTRIBUTING.md:

https://github.com/pubtestme/pubtestme.github.io/blame/master/CONTRIBUTING.md#L4

`permalink` makes jekyll generate a page for the provided path.

The link has worked for me at least, was it broken for you?

**Comment by mazzone** [comment]
Yes, it just gives me a 404 (still).  Is it working for you?

**Comment by amboar** [comment]
How are you testing? I just checked the live site in Firefox Focus and the link works for me. Does one of us have a caching issue?

**Comment by mazzone** [comment]
I get a 404 on Firefox 72.06 and 73, and Chrome 79.0.3945.130.

Does the link take you to https://github.com/pubtestme/pubtestme.github.io/blob/master/contributing ?

**Comment by amboar** [comment]
Ah, I've figured out what's going on here. This is what I was talking about:

Screenshot from 2020-02-12 09-52-47

But you're talking about:

Screenshot from 2020-02-12 09-56-23

I'll test this pull-req later.

**Comment by mazzone** [comment]
Ah, or course! I didn't even think to test the rendered version!
Thanks.

**Comment by amboar** [comment]
Alright, your patch works for both, merging. Thanks!

**Comment by amboar** [comment]
I've merged it locally and pushed. Did so to fix up the missing S-o-b.

**Pull request closed without merging**
